name: Changes
on:
  workflow_call:
    outputs:
      api:
        value: ${{ jobs.changes.outputs.api }}
      client:
        value: ${{ jobs.changes.outputs.client }}

jobs:
  changes:
    name: filter
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - name: 'Setup Node'
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Checkout
        uses: https://gitea.com/actions/checkout@v6
        with:
          repository: noah/noahspan-flying
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
            client:
              - 'client/**'