name: Changes
on:
  workflow_call:
    outputs:
      api:
        value: ${{ jobs.changes.outputs.api }}
      client:
        value: ${{ jobs.changes.outputs.client }}

permissions:
  contents: read

jobs:
  changes:
    name: filter
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      # - name: 'Setup Node'
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: '2.x'

      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     path: noahspan-flying

      - name: Manual Git Clone
        run: |
          # Use GITEA_TOKEN for the current repo or a PAT for others
          git clone http://gitea:3000/${{ gitea.repository }}.git .

      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      
      # - uses: dorny/paths-filter@v3
      #   id: filter
      #   with:
      #     filters: |
      #       api:
      #         - 'api/**'
      #       client:
      #         - 'client/**'