name: Pull Request

on:
  pull_request:

jobs:
  changes:
    uses: ./.gitea/workflows/changes.yaml

  build:
    if: ${{ needs.changes.outputs.api == 'true' || needs.changes.outputs.client == 'true'}}
    name: build-and-test
    needs:
      - changes
    uses: ./.gitea/workflows/build_and_test.yaml
    with:
      environment_name: test
      version_number: ${{ github.run_id }}
    secrets: inherit

  terraform:
    if: ${{ needs.changes.outputs.infrastructure == 'true' }}
    name: terraform-plan
    needs: 
      - changes
    uses: ./.gitea/workflows/infrastructure.yaml
    with:
      environment_name: test
    secrets: inherit
