name: Tag
on:
  push:
    tags:
      - '**'

jobs:
  build-and-test:
    name: build-and-test
    uses: ./.gitea/workflows/build_and_test.yaml
    with:
      environment_name: prod
      version_number: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    name: deploy
    needs: 
      - build-and-test
    uses: ./.gitea/workflows/deploy.yaml
    with:
      app_name: flying
      environment_name: prod
      version_number: ${{ github.ref_name }}
    secrets: inherit
