name: 'API Build'
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      version_number:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            api

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Nest CLI
        run: |
          npm install -g @nestjs/cli

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm --filter api build

      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          pnpm --filter api --prod deploy ./.prod/api

      - name: Log into Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and push to registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: noahspan/flying-api:${{ inputs.version_number }}
          context: .
          target: api
