name: 'App Build'
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      version_number:
        required: true
        type: string

env:
  VITE_API_URL: "https://flying-api-test.internal.lemonflower-48c61d49.centralus.azurecontainerapps.io"
  VITE_CLIENT_ID: "d3562a45-050d-4f9a-baed-0497c7156924"
  VITE_TENANT_ID: "0f23652e-4b15-420f-991e-3d6fc769a31d"
  VITE_REDIRECT_URL: "https://flying-app-test.lemonflower-48c61d49.centralus.azurecontainerapps.io"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.calling_workflow }}
    steps:
      - run: |
          printenv

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            app

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm --filter app build

      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          pnpm --filter app --prod deploy ./.prod/app

      - name: Setup Docker Buildx
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: noahspan/flying-app:${{ inputs.version_number }}
          context: .
          target: app
