name: Dev
on:
  push:
    branches:
      - feature/**

jobs:
  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: 'true'

  build-deploy-api:
    if: contains(needs.changed-files.outputs.modified_files, 'api')
    name: build-deploy-api
    needs:
      - changed-files
    uses: ./.github/workflows/api.yaml
    with:
      calling_workflow: dev
    secrets: inherit

  build-deploy-app:
    if: contains(needs.changed-files.outputs.modified_files, 'app')
    name: build-deploy-app
    needs:
      - changed-files
    uses: ./.github/workflows/app.yaml
    with:
      calling_workflow: dev
      deployment_environment: development
    secrets: inherit
