name: Dev
on:
  push:
    branches:
      - feature/**

jobs:
  build-deploy-api:
    name: build-deploy-api
    uses: ./.github/workflows/api.yaml
    with:
      calling_workflow: dev
    secrets: inherit

  build-deploy-app:
    name: build-deploy-app
    uses: ./.github/workflows/app.yaml
    with:
      calling_workflow: dev
      deployment_environment: development
    secrets: inherit
