name: Feature

on:
    push:
        branches:
            - feature/**

jobs:
    build_and_deploy_job:
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
            
            - name: Build and Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                action: "upload"
                app_location: "/"
                app_build_command: 'npm run build-storybook'
                api_location: ""
                output_location: "storybook-static"
                deployment_environment: "development"
                